### ISSUE TITLE
Zulu jmc is broken on Linux 

### ISSUE THREAD

**Issue by rvprasad** [sdkman/sdkman-hooks#39]
The `jmc` symbolic link to `zmc` in **8.1.1.51-zulu** version of JMC on Linux should be `../Azul Mission Control/zmc` (instead of being `../Zulu Mission Control/zmc`).

I am guessing https://github.com/sdkman/sdkman-hooks/blob/980175e18030828cb957dc05010d82dbb3150b73/app/controllers/HooksController.scala#L102-L111 needs to be tweaked to fix this issue.

**Comment by marc0der** [comment]
@rvprasad I'm happy to accept a PR for this if you would like to fix it. I'm guessing it's also not only broken on Linux.
