### ISSUE TITLE
Installer: remove check for presence of `zip`

### ISSUE THREAD

**Issue by mickroll** [sdkman/sdkman-hooks#42]
currently, the installer checks for presence of `zip`:
https://github.com/sdkman/sdkman-hooks/blob/afbc9f780c8045d8e252581c4c538de68442367d/app/views/install_stable.scala.txt#L151-L161

But the installer does not make use of `zip`. It only uses `unzip`, whose presence is checked separately.

Please remove the unneeded check for `zip`.

**Comment by christianhujer** [comment]
The unneeded check for `zip` will allow the use of SDKMAN! in plain Windows git bash without the need of installing any additional tools.

Currently, I use the following workaround to get SDKMAN! working on Windows:
```bash
mkdir -p ~/bin/
cp $(which unzip) ~/bin/zip
```
SDKMAN! seems to work just fine with this workaround.

After the removal of the unnecessary check for `zip`, this workaround would no longer be needed.

**Comment by marc0der** [comment]
The reason we do these checks in the installer is that `zip` is a required dependency for repackaging tarballs as zips in the `archives` directory as @christianhujer pointed out. This is used in several candidates including Java and JMC. Not having `zip` will cause failure, so hence this mandatory condition.

Here's an excerpt from our [installation page](https://sdkman.io/install) on our website:

> The third solution is for Git users using the [Git Bash for Windows](https://git-scm.com/download/win) environment. In order for this to work, the environment needs to be supplemented with [MinGW](https://www.mingw-w64.org/) to add the necessary toolchain to function.

By supplementing your git bash setup with MinGW, you will have all the tools you need to successfully run SDKMAN. That includes the approved InfoZip `zip` binary.

**Comment by mickroll** [comment]
So installing sdkman enforces tool presence, that only a few packages will need.

If this is how it is intended to be, ok.
